### ISSUE TITLE
Error with Gutenberg 7.2.0: Block validation: Block validation failed for `core/html` 

### ISSUE THREAD

**Issue by DanWahlin** [maximebj/agb.plugin#47]
First off - thanks for your great work on this plugin! I've really enjoyed using it - great job.

I recently updated my blog to use Gutenberg 7.2.0 and with Advanced Gutenberg Blocks enabled the following error now shows in the devtools console when I try to edit a block in a post:

Block validation: Block validation failed for `core/html` (
{name: "core/html", icon: {…}, attributes: {…}, keywords: Array(1), save: ƒ, …}
name: "core/html"
icon: {src: {…}}
attributes: {content: {…}}
keywords: ["embed"]
save: ƒ (e)
category: "formatting"
title: "Custom HTML"
description: "Add custom HTML code and preview it as you edit."
example: {attributes: {…}}
supports: {customClassName: false, className: false, html: false}
transforms: {from: Array(1)}
edit: ƒ n()
__proto__: Object

I'm also seeing this error after clicking on an existing block:

Error: Cannot bind alt+c. Alt and Shift+Alt modifiers are reserved for character input.
    at index.js?ver=03b5f6921d69ba216629f9b6c1d83fd0:1
    at Array.forEach (<anonymous>)
    at index.js?ver=03b5f6921d69ba216629f9b6c1d83fd0:1
    at Vb (react-dom.min.b694e242.js?ver=16.9.0:104)
    at Xi (react-dom.min.b694e242.js?ver=16.9.0:151)
    at unstable_runWithPriority (react.min.0212dc62.js?ver=16.9.0:26)
    at Ma (react-dom.min.b694e242.js?ver=16.9.0:52)
    at Yb (react-dom.min.b694e242.js?ver=16.9.0:150)
    at O (react-dom.min.b694e242.js?ver=16.9.0:120)
    at ze (react-dom.min.b694e242.js?ver=16.9.0:118)

After that I get the "This block has encountered an error and cannot be previewed." message. If I disable Advanced Gutenberg Blocks I can edit the post again but all of my custom code blocks break and aren't displayed in a given post of course. I've worked around it by using another custom code block plugin but it's not nearly as good as yours so I wanted to pass along the error info in hopes of getting it working again.

![2020-01-21_17-56-40](https://user-images.githubusercontent.com/1767249/72856329-77636980-3c77-11ea-9d64-03e0982f5dd8.png)

![2020-01-21_17-57-33](https://user-images.githubusercontent.com/1767249/72856352-821dfe80-3c77-11ea-83ae-47a38c407239.png)

![2020-01-21_17-57-56](https://user-images.githubusercontent.com/1767249/72856374-9235de00-3c77-11ea-8b20-cab6223be563.png)

**Comment by maximebj** [comment]
Hi ! I have to make some tests because a lot of things have changed in Gutenberg core and some of my code maybe outdated. 
I'll try to fix this ASAP. I never encountered this error though, I don't interact with html field. But I'll take a closer look

**Comment by DanWahlin** [comment]
If Gutenberg core is changing a lot that's definitely a pain to deal with (speaking as a fellow software developer). Regardless, thanks again for your work on this project - great stuff!

If you need any other details just let me know. The "This block has encountered an error and cannot be previewed" error seems to happen on paragraph blocks, headings, etc. It doesn't seem to affect my image blocks or code blocks though. 

I do have a lot of other plugins installed but seem to be able to isolate this issue to the latest version of Gutenberg (7.3.0 just came out this morning...still seeing the same error with it as well) and the latest version of the Advanced Blocks (I have 1.9.4).

**Comment by maximebj** [comment]
WP Core is proud of its "retrocompatibility" but that's not the same with Gutenberg. I also got a few free time to handle well this plugin.

Thanks for the details, it'll help!

**Comment by DanWahlin** [comment]
Nothing more fun than having a moving target. :-) 

Thanks for looking into it. No rush on it. I have several open source projects as well so I understand time limitations. But, if you do find anything or need more info let me know.

**Comment by maximebj** [comment]
I can't reproduce the issue right now. I think my recents devs have fixed the issue. Feel free to reopen if the error persists after the tomorrow update.

**Comment by DanWahlin** [comment]
Thanks - I'll check out the update.
