### ISSUE TITLE
Additional css classes ignored?

### ISSUE THREAD

**Issue by Theremingenieur** [maximebj/agb.plugin#48]
When you add an additional css class to whatever Gutenberg block in the advanced block settings, that class is normally added to the class=”whatever_classes” string of the block tag during html output. That works with all Gutenberg blocks, but apparently NOT with the Advanced Gutenberg Post block (did not yet test with other blocks from Maxime’s otherwise great plugin). The additional class(es) are simply not output 🙁

Actual html output:
`<div class="wp-block-advanced-gutenberg-blocks-post">`
Expected html output:
`<div class="wp-block-advanced-gutenberg-blocks-post my-class">`

Thus, I can’t re-style your single post block, which is sad since I finally found a css way to make the post block render vertically (picture above the text) to put 2 or 3 post blocks in columns.

**Comment by maximebj** [comment]
The Block Editor automatically adds classnames here. I've tested it and I can see custom classes in my blocks. But when a block is rendered in PHP (which is the case for post blocks). I have to add a little code to get the custom class indeed.

I've found a way to fix it, I'm releasing a new version tomorrow
