### ISSUE TITLE
Could you please use spaces or tabs

### ISSUE THREAD

**Issue by mahnunchik** [maximebj/agb.plugin#52]
Could you please use spaces or tabs, not both the same file: https://github.com/maximebj/agb.plugin/blob/master/src/blocks/summary/index.js#L24-L39

Or activate editorconfig plugin you already setup: https://github.com/maximebj/agb.plugin/blob/master/.editorconfig#L14

**Comment by maximebj** [comment]
Yep. 
I'm not sure why it didn't worked well until now but I'll try to clean this up for the next release

**Comment by mahnunchik** [comment]
It depends of IDE and editorconfig plugin you use sometimes it doesn't fix old files.

**Comment by maximebj** [comment]
I had several issues with VSC and had to disable plugins for a while. I'll try a prettifier or something like that

**Comment by maximebj** [comment]
I'll try to fix this in next releases
