### ISSUE TITLE
Undo doesn't work with Table of Contents block

### ISSUE THREAD

**Issue by ZebulanStanphill** [maximebj/agb.plugin#53]
## The issue
When using a Table of Contents block, the Undo function in the block editor doesn't work.

## How to reproduce
1. Insert a Table of Contents block.
2. Create some Heading blocks.
3. Try to use the Undo button in the top toolbar.

## Additional notes
I discovered this while trying out this plugin to see if I could find some solutions for bugs in the current implementation of a [core Table of Contents block PR](https://github.com/WordPress/gutenberg/pull/21234) that I and several others are working on. For reference, the current implementation in the PR has working undo, but it creates 2 undo steps (rather than the ideal of only 1) for each change to the content of a Heading block.

**Comment by maximebj** [comment]
I can reproduce the issue, and it's very annoying. 
Also I use a light version of the Gutenberg code to get the headings (the process that initially list all headings in the top of the editor). 
For now it cannot list heading in groups and columns. So I need to improve this a lot.

It would be awesome if such a block finishes in the core.

**Comment by maximebj** [comment]
Tell me if a solution shows up because it's beyond my coding level!

**Comment by ZebulanStanphill** [comment]
@maximebj My [table of contents block PR](https://github.com/WordPress/gutenberg/pull/21234) for the Gutenberg project is now in as good a state as it can get without [additional APIs](https://github.com/WordPress/gutenberg/pull/21234) being introduced. It doesn't have the undo problem, and really, the only problem it does have is an edge-case issue with `<!--nextpage-->` tags not being counted correctly in the editor (the front end is fine), which I don't think your implementation even attempts to handle in the first place.

Because of the aforementioned edge-cases, I've avoided merging the block into core, but I think the implementation is fine for a plugin, so feel free to copy anything from my implementation to improve or fix your own.
